language: none

branches:
  only:
    - master

build:
  ci:
    - git remote set-url origin git@github.com:justin8/mediaserver-stack.git
    # Update branches
    - ./.shippable-update-branch pia-armhf
    - ./.shippable-update-branch pia-x86
    - ./.shippable-update-branch torguard-x86

integrations:
  key:
    - integrationName: shippable-mediaserver-stack-deploy-key
      type: ssh-key
