version: "3"

services:
    vpn:
        image: justin8/pia-openvpn:armhf
        network_mode: bridge
        privileged: true
        entrypoint:
          - sh
          - -c
          - echo "nameserver 8.8.8.8" > /etc/resolv.conf; openvpn.sh
        environment:
          - "REGION=AU Sydney"
          - "USERNAME=$VPN_USER"
          - "PASSWORD=$VPN_PASS"
        healthcheck:
          test: "wget http://www.google.com -O /dev/null"
    transmission:
        image: lsioarmhf/transmission
        network_mode: "service:vpn"
        environment:
          - "PGID=${PGID}"
          - "PUID=${PUID}"
        depends_on:
            - vpn
        volumes:
          - $CONFIG_DIR/transmission:/config:rw
          - ${STORAGE_DIR}:${STORAGE_DIR}:rw
        healthcheck:
          test: "curl -ILXGET http://localhost:9091"
    sonarr:
        build:
          context: .
          dockerfile: sonarr-dockerfile
        network_mode: "service:vpn"
        environment:
          - "PGID=${PGID}"
          - "PUID=${PUID}"
        depends_on:
          - vpn
          - jackett
        volumes:
          - $CONFIG_DIR/sonarr:/config:rw
          - ${STORAGE_DIR}:${STORAGE_DIR}:rw
        healthcheck:
          test: "curl -ILXGET http://localhost:8989"
    radarr:
        build:
          context: .
          dockerfile: radarr-dockerfile
        network_mode: "service:vpn"
        environment:
          - "PGID=${PGID}"
          - "PUID=${PUID}"
        depends_on:
          - vpn
          - jackett
        volumes:
          - $CONFIG_DIR/radarr:/config
          - ${STORAGE_DIR}:${STORAGE_DIR}:rw
        healthcheck:
          test: "curl -ILXGET http://localhost:7878"
    jackett:
        image: lsioarmhf/jackett
        network_mode: "service:vpn"
        environment:
          - "PGID=${PGID}"
          - "PUID=${PUID}"
        depends_on:
          - vpn
        volumes:
          - $CONFIG_DIR/jackett:/config
        healthcheck:
          test: "curl -ILXGET http://localhost:9117"
    nginx:
        image: justin8/simple-proxy:armhf
        network_mode: bridge
        environment:
          - "DNS_TLD=$DNS_TLD"
          - "PROXY_PORT=${PORT}"
          - "PROXY_ENDPOINTS=transmission,vpn:9091;jackett,vpn:9117;sonarr,vpn:8989;radarr,vpn:7878"
          - "VIRTUAL_PORT=${PORT}"
          - "VIRTUAL_HOST=transmission.${DNS_TLD},sonarr.${DNS_TLD},jackett.${DNS_TLD},radarr.${DNS_TLD}"
          - "LETSENCRYPT_HOST=transmission.${DNS_TLD},sonarr.${DNS_TLD},jackett.${DNS_TLD},radarr.${DNS_TLD}"
          - "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
        ports:
          - "${PORT}:${PORT}"
        depends_on:
          - vpn
        links:
          - vpn
