version: "3"

services:
    vpn:
        image: colinhebert/pia-openvpn
        network_mode: bridge
        privileged: true
        entrypoint:
          - sh
          - -c
          - echo "nameserver 8.8.8.8" > /etc/resolv.conf; openvpn.sh
        environment:
          - "REGION=AU Sydney"
          - "USERNAME=$VPN_USER"
          - "PASSWORD=$VPN_PASS"
        healthcheck:
          test: "wget http://www.google.com -O /dev/null"
    transmission:
        image: linuxserver/transmission
        network_mode: "service:vpn"
        environment:
          - "PGID=${GID}"
          - "PUID=${UID}"
        depends_on:
            - vpn
        volumes:
          - $CONFIG_DIR/transmission:/config:rw
          - ${STORAGE_DIR}:${STORAGE_DIR}:rw
        healthcheck:
          test: "curl -ILXGET http://localhost:9091"
    sonarr:
        image: linuxserver/sonarr
        network_mode: "service:vpn"
        environment:
          - "PGID=${GID}"
          - "PUID=${UID}"
        depends_on:
          - vpn
          - jackett
        volumes:
          - $CONFIG_DIR/sonarr:/config:rw
          - ${STORAGE_DIR}:${STORAGE_DIR}:rw
        healthcheck:
          test: "curl -ILXGET http://localhost:8989"
    couchpotato:
        image: linuxserver/couchpotato
        network_mode: "service:vpn"
        environment:
          - "PGID=${GID}"
          - "PUID=${UID}"
        depends_on:
          - vpn
          - jackett
        volumes:
          - $CONFIG_DIR/couchpotato:/config
          - ${STORAGE_DIR}:${STORAGE_DIR}:rw
        healthcheck:
          test: "curl -ILXGET http://localhost:5050/login"
    jackett:
        image: linuxserver/jackett
        network_mode: "service:vpn"
        environment:
          - "PGID=${GID}"
          - "PUID=${UID}"
        depends_on:
          - vpn
        volumes:
          - $CONFIG_DIR/jackett:/config
        healthcheck:
          test: "curl -ILXGET http://localhost:9117"
    nginx:
        image: justin8/simple-proxy
        network_mode: bridge
        environment:
          - "DNS_TLD=$DNS_TLD"
          - "VIRTUAL_PORT=8080"
          - "VIRTUAL_HOST=transmission.${DNS_TLD},sonarr.${DNS_TLD},couchpotato.${DNS_TLD},jackett.${DNS_TLD}"
          - "LETSENCRYPT_HOST=transmission.${DNS_TLD},sonarr.${DNS_TLD},couchpotato.${DNS_TLD},jackett.${DNS_TLD}"
          - "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
        volumes:
          - ./nginx-config.yml:/config.yml:ro
        ports:
          - "8080:8080"
        depends_on:
          - vpn
        links:
          - vpn
