version: '2'

services:
    vpn:
        image: colinhebert/pia-openvpn
        restart: always
        privileged: true
        entrypoint:
          - sh
          - -c
          - echo 'nameserver 8.8.8.8' > /etc/resolv.conf; openvpn.sh
        environment:
          - 'REGION=AU Sydney'
          - 'USERNAME=$VPN_USER'
          - 'PASSWORD=$VPN_PASS'
    transmission:
        image: linuxserver/transmission
        restart: always
        network_mode: "service:vpn"
        environment:
          - 'PGID=0'
          - 'PUID=0'
        depends_on:
            - vpn
        volumes:
          - $CONFIG_DIR/transmission:/config:rw
          - $STORAGE_MOUNT
    sonarr:
        image: linuxserver/sonarr
        restart: always
        network_mode: "service:vpn"
        environment:
          - 'PGID=0'
          - 'PUID=0'
        depends_on:
          - vpn
          - jackett
        volumes:
          - $CONFIG_DIR/sonarr:/config:rw
          - $STORAGE_MOUNT
    couchpotato:
        image: linuxserver/couchpotato
        restart: always
        network_mode: "service:vpn"
        environment:
          - 'PGID=0'
          - 'PUID=0'
        depends_on:
          - vpn
          - jackett
        volumes:
          - $CONFIG_DIR/couchpotato:/config
          - $STORAGE_MOUNT
    jackett:
        image: linuxserver/jackett
        restart: always
        network_mode: "service:vpn"
        environment:
          - 'PGID=0'
          - 'PUID=0'
        depends_on:
          - vpn
        volumes:
          - $CONFIG_DIR/jackett:/config
    nginx:
        image: nginx
        restart: always
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./nginx:/nginx:ro
          - ./nginx/conf.d:/etc/nginx/conf.d:ro
          - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
          - /var/log/nginx:/var/log/nginx:rw
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - vpn
        links:
          - vpn
